/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.clientesocketmedicion.vista;

import co.unicauca.clientesocketsmedicion.principal.ClienteMedicion;
import com.mycompany.sistemaservidorclientecomun.Objeto;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanc
 */
public class InterfazGrafica extends javax.swing.JFrame {

    ClienteMedicion cm = new ClienteMedicion();
    
    /**
     * Creates new form InterfazGrafica
     */
    public InterfazGrafica() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Titulo = new javax.swing.JLabel();
        lbl_S_Altura = new javax.swing.JLabel();
        lbl_S_Diametro = new javax.swing.JLabel();
        lbl_S_Peso = new javax.swing.JLabel();
        lbl_S_Tipo = new javax.swing.JLabel();
        Rbt_Cerveza = new javax.swing.JRadioButton();
        Rbt_Gaseosa = new javax.swing.JRadioButton();
        jtxtS_Altura = new javax.swing.JTextField();
        jtxtS_Diametro = new javax.swing.JTextField();
        jtxtS_Peso = new javax.swing.JTextField();
        Btn_Evaluar = new javax.swing.JButton();
        jtxt_Respuesta = new javax.swing.JTextField();
        lbl_Ref = new javax.swing.JLabel();
        jtxt_Ref = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtb_Informacion_Ingresada = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtb_Informacion_Ingresada2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_Titulo.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_Titulo.setText("Mediciones de calidad");

        lbl_S_Altura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_S_Altura.setText("Sensor Altura");

        lbl_S_Diametro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_S_Diametro.setText("Sensor Diametro");

        lbl_S_Peso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_S_Peso.setText("Sensor Peso");

        lbl_S_Tipo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_S_Tipo.setText("Tipo :");

        Rbt_Cerveza.setText("Cerveza");
        Rbt_Cerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Rbt_CervezaActionPerformed(evt);
            }
        });

        Rbt_Gaseosa.setText("Gaseosa");

        Btn_Evaluar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Btn_Evaluar.setText("Evaluar");
        Btn_Evaluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EvaluarActionPerformed(evt);
            }
        });

        jtxt_Respuesta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        lbl_Ref.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Ref.setText("Referencia");

        jtb_Informacion_Ingresada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtb_Informacion_Ingresada);

        jLabel1.setText("Aceptados");

        jLabel2.setText("Defectuosos");

        jtb_Informacion_Ingresada2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtb_Informacion_Ingresada2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lbl_S_Altura, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_S_Peso, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbl_S_Diametro)
                            .addGap(79, 79, 79)
                            .addComponent(jtxtS_Diametro, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lbl_Ref)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxt_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbl_S_Tipo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Rbt_Cerveza)
                            .addGap(29, 29, 29)
                            .addComponent(Rbt_Gaseosa))
                        .addComponent(jtxtS_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtxtS_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(Btn_Evaluar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbl_Titulo)))
                .addGap(290, 290, 290))
            .addGroup(layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(jtxt_Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbl_Titulo)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Ref)
                    .addComponent(jtxt_Ref, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_S_Altura)
                    .addComponent(jtxtS_Altura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_S_Diametro)
                    .addComponent(jtxtS_Diametro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_S_Peso)
                    .addComponent(jtxtS_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rbt_Cerveza)
                    .addComponent(Rbt_Gaseosa)
                    .addComponent(lbl_S_Tipo))
                .addGap(32, 32, 32)
                .addComponent(Btn_Evaluar)
                .addGap(18, 18, 18)
                .addComponent(jtxt_Respuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Rbt_CervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Rbt_CervezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Rbt_CervezaActionPerformed

    private void Btn_EvaluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EvaluarActionPerformed
        
        try{          
            int referencia = Integer.parseInt(jtxt_Ref.getText());
            float peso = Float.parseFloat(jtxtS_Peso.getText());
            float diametro = Float.parseFloat(jtxtS_Diametro.getText());
            float largo = Float.parseFloat(jtxtS_Altura.getText());
            boolean c = Rbt_Cerveza.isSelected();
            if(referencia >= 0 && peso > 0 && diametro > 0 && largo > 0 && Rbt_Cerveza.isSelected()){
                Objeto o = new Objeto(referencia, largo, diametro, peso, c);
                limpiarCampos();
                cm.iniciarConexionCliente(o);

                //llenado de tabla defectuosas
                if(!cm.getAceptados().isEmpty()){
                    String colum []={"Referencia","Largo","Diametro","Peso"};
                    String datos[][] = new String[cm.getAceptados().size()][4];
                    for(int j=0;j<cm.getAceptados().size();j++){
                        datos[j][0]= ""+cm.getAceptados().get(j).getReferencia();
                        datos[j][1]= ""+cm.getAceptados().get(j).getLargo();
                        datos[j][2]= ""+cm.getAceptados().get(j).getDiametro();
                        datos[j][3]= ""+cm.getAceptados().get(j).getPeso();
                    }
                    jtb_Informacion_Ingresada2.setModel(new DefaultTableModel(datos,colum));
                }

                //llenado de tabla defectuosas
                String NombreColumnas []={"Referencia","Largo","Diametro","Peso"};
                String data[][] = new String[cm.getDefectuosos().size()][4];
                for(int i=0;i<cm.getDefectuosos().size();i++){
                    data[i][0]= ""+cm.getDefectuosos().get(i).getReferencia();
                    data[i][1]= ""+cm.getDefectuosos().get(i).getLargo();
                    data[i][2]= ""+cm.getDefectuosos().get(i).getDiametro();
                    data[i][3]= ""+cm.getDefectuosos().get(i).getPeso();
                }
                jtb_Informacion_Ingresada.setModel(new DefaultTableModel(data,NombreColumnas));



                jtxt_Respuesta.setText(cm.getEp());
            } 
            
            
        }catch(NumberFormatException ne){
            jtxt_Respuesta.setText("Agregue datos validos para la medicion");
        }
        
        
    }//GEN-LAST:event_Btn_EvaluarActionPerformed

    private void limpiarCampos(){
    jtxt_Ref.setText("");
    jtxtS_Altura.setText("");
    jtxtS_Diametro.setText("");
    jtxtS_Peso.setText("");
    
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Evaluar;
    private javax.swing.JRadioButton Rbt_Cerveza;
    private javax.swing.JRadioButton Rbt_Gaseosa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jtb_Informacion_Ingresada;
    private javax.swing.JTable jtb_Informacion_Ingresada2;
    private javax.swing.JTextField jtxtS_Altura;
    private javax.swing.JTextField jtxtS_Diametro;
    private javax.swing.JTextField jtxtS_Peso;
    private javax.swing.JTextField jtxt_Ref;
    private javax.swing.JTextField jtxt_Respuesta;
    private javax.swing.JLabel lbl_Ref;
    private javax.swing.JLabel lbl_S_Altura;
    private javax.swing.JLabel lbl_S_Diametro;
    private javax.swing.JLabel lbl_S_Peso;
    private javax.swing.JLabel lbl_S_Tipo;
    private javax.swing.JLabel lbl_Titulo;
    // End of variables declaration//GEN-END:variables
}
